package beca;


/**
* beca/BecaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Beca.idl
* jueves 22 de noviembre de 2018 01:20:20 PM CST
*/

public interface BecaOperations 
{
  beca.Llistado[] getListado (String cs);
  double getPromedioListado (String cs);
} // interface BecaOperations
